<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/**
 * @file
 * Main module file for Apigee Open Bank Kickstart Enhancement.
 */

use Drupal\apigee_openbank_kickstart_enhancement\Entity\ApiDocViewBuilder;
use Drupal\apigee_openbank_kickstart_enhancement\Entity\AppViewBuilder;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Menu\LocalActionDefault;

/*
 * Load all theme functions.
 */
require_once __DIR__ . '/apigee_openbank_kickstart_enhancement.theme.inc';

/**
 * Implements hook_theme().
 */
function apigee_openbank_kickstart_enhancement_theme($existing, $type, $theme, $path) {
  return [
    'app' => [
      'render element' => 'elements',
      'file' => 'apigee_openbank_kickstart_enhancement.theme.inc',
    ],
    'apidoc' => [
      'render element' => 'elements',
      'file' => 'apigee_openbank_kickstart_enhancement.theme.inc',
    ],
    'secret' => [
      'render element' => 'elements',
      'file' => 'apigee_openbank_kickstart_enhancement.theme.inc',
    ],
    'api_explorer' => [
      'variables' => [
        'items' => [],
        'base_path' => substr(base_path(), 0, -1),
      ],
    ],
  ];
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function apigee_openbank_kickstart_enhancement_menu_local_actions_alter(&$local_actions) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface $app_entity_type */
  foreach (\Drupal::service('apigee_openbank_kickstart.enhancer')->getAppEntityTypes() as $entity_type_id => $app_entity_type) {
    // Update the local action title for app entity types.
    $local_action_name = $app_entity_type->getProvider() . ".$entity_type_id.add_form_for_" . str_replace('_app', '', $entity_type_id);
    if (isset($local_actions[$local_action_name])) {
      $local_actions[$local_action_name]['title'] = t('Register new @entity_type', [
        '@entity_type' => $app_entity_type->getLowercaseLabel(),
      ]);

      // Setting the title with entity type label is handled above.
      // So we can fallback to the default class here.
      $local_actions[$local_action_name]['class'] = LocalActionDefault::class;
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function apigee_openbank_kickstart_enhancement_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if (\Drupal::service('apigee_openbank_kickstart.enhancer')->isAppEntityType($entity_type)) {
      // Update the view builder handler.
      $entity_types[$entity_type_id]->setViewBuilderClass(AppViewBuilder::class);
    }
  }

  // TODO: Figure out if we need this for other entities and consolidate all
  // entities in one ViewBuilder.
  if (isset($entity_types['apidoc'])) {
    $entity_types['apidoc']->setViewBuilderClass(ApiDocViewBuilder::class);
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function apigee_openbank_kickstart_enhancement_entity_extra_field_info() {
  // Make the user display name configurable.
  // In Apigee Edge, this is the entity label.
  $fields['user']['user']['display']['display_name'] = [
    'label' => t('Name'),
    'description' => t('The name from Apigee Edge.'),
    'weight' => -10,
    'visible' => TRUE,
  ];

  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function apigee_openbank_kickstart_enhancement_user_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('display_name')) {
    $build['display_name'] = [
      '#markup' => $entity->label(),
    ];
  }
}
