<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/**
 * @file
 * Main module file for Apigee Kickstart Enhancement.
 */

use Drupal\apigee_kickstart_enhancement\Entity\AppViewBuilder;
use Drupal\Core\Menu\LocalActionDefault;

/*
 * Load all theme functions.
 */
require_once __DIR__ . '/apigee_kickstart_enhancement.theme.inc';

/**
 * Implements hook_theme().
 */
function apigee_kickstart_enhancement_theme($existing, $type, $theme, $path) {
  return [
    'app' => [
      'render element' => 'elements',
      'file' => 'apigee_kickstart_enhancement.theme.inc',
    ],
    'secret' => [
      'render element' => 'elements',
      'file' => 'apigee_kickstart_enhancement.theme.inc',
    ],
  ];
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function apigee_kickstart_enhancement_menu_local_actions_alter(&$local_actions) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface $app_entity_type */
  foreach (\Drupal::service('apigee_kickstart.enhancer')->getAppEntityTypes() as $entity_type_id => $app_entity_type) {
    // Update the local action title for app entity types.
    $local_action_name = $app_entity_type->getProvider() . ".$entity_type_id.add_form_for_" . str_replace('_app', '', $entity_type_id);
    if (isset($local_actions[$local_action_name])) {
      $local_actions[$local_action_name]['title'] = t('Register new @entity_type', [
        '@entity_type' => $app_entity_type->getLowercaseLabel(),
      ]);

      // Setting the title with entity type label is handled above.
      // So we can fallback to the default class here.
      $local_actions[$local_action_name]['class'] = LocalActionDefault::class;
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function apigee_kickstart_enhancement_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if (\Drupal::service('apigee_kickstart.enhancer')->isAppEntityType($entity_type)) {
      // Update the view builder handler.
      $entity_types[$entity_type_id]->setViewBuilderClass(AppViewBuilder::class);
    }
  }
}
